version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: dcn-api
    container_name: dcn-api
    ports:
      - 3000:3000
    entrypoint: sh -c "node index.js"