version: '3.7'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: dcn-client
    container_name: dcn-client
    environment:
      SERVER_URL: "http://host.docker.internal:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"